# version: "3"

# services:
#   namenode:
#     image: strongpapazola/hadoop-namenode:3.3.4-java8
#     container_name: namenode
#     hostname: namenode
#     # hostname: bigdata.bisa.ai
#     restart: always
#     ports:
#       - 9870:9870
#       - 9000:9000
#     volumes:
#       - hadoop_namenode:/hadoop/dfs/name
#     environment:
#       - CLUSTER_NAME=mycluster
#     env_file:
#       - ./hadoop.env
#     networks:
#       - development


# networks:
#   development:
#     name: development
#     driver: bridge

version: '3'
services:
  spark-master:
    image: strongpapazola/hadoop-spark-master:3.3.4-java8
    container_name: spark-master
    env_file:
      - ./hadoop.env
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - development
  spark-worker-1:
    image: strongpapazola/hadoop-spark-worker:3.3.4-java8
    container_name: spark-worker-1
    env_file:
      - ./hadoop.env
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - development
  
networks:
  development:
    name: development
    driver: bridge
